package com.power222.tuimspfcauppbj.util;

public enum EmailContentsType {
    NOTIFY_ABOUT_NEW_CONTRACT,
    NOTIFY_ABOUT_CONTRACT_DELETION,
    NOTIFY_ABOUT_NEW_SIGNATURE,
    NOTIFY_ABOUT_CONTRACT_REJECTION,
    NOTIFY_AND_ATTACH_SIGNED_CONTRACT,
    NOTIFY_ABOUT_EVALUATION_CREATED
}
