package com.power222.tuimspfcauppbj.util;

public enum StudentApplicationState {
    APPLICATION_PENDING_FOR_EMPLOYER_INITIAL_REVIEW,
    APPLICATION_REJECTED_BY_EMPLOYER,
    STUDENT_INVITED_FOR_INTERVIEW_BY_EMPLOYER,
    WAITING_FOR_EMPLOYER_HIRING_FINAL_DECISION,
    STUDENT_HIRED_BY_EMPLOYER,
    STUDENT_REJECTED_BY_EMPLOYER,
    JOB_OFFER_ACCEPTED_BY_STUDENT,
    JOB_OFFER_DENIED_BY_STUDENT
}
